### PR TITLE
Adding DataProfiler as a Text Library

### PR DESCRIPTION
**Pull request by micdavis**

### CODE REVIEW

**Comment by taylorfturner** [comment]
Not quite certain if `Data Profiler` should go under `Libraries/text` or if we should create a new section under `Libraries`
CC @micdavis and @JGSweets

**Comment by JGSweets** [comment]
@jsbroks any movement on this? Thanks!

**Comment by taylorfturner** [comment]
@jsbroks bump on this. Thx!

**Comment by taylorfturner** [comment]
@jsbroks bump on this. Thx!

**Review by jsbroks — APPROVED** [review]

**Pull request merged**
